// Starting content for a fresh Supabase project — the same content the site
// shipped with before the admin panel existed. Run once via `npm run db:seed`.
// After seeding, this file is no longer the source of truth: edit content
// through /admin instead.

export const projects = [
  {
    slug: "jobify",
    title: "Jobify",
    category: "Product · Job Matching",
    description:
      "A job platform that ranks listings by fit instead of recency, with real-time notifications and dynamic search filters.",
    stack: ["Java", "Spring Boot", "React.js", "MySQL"],
    visual: "product-ui",
    problem:
      "Generic job boards surface listings by recency or keyword match, which buries relevant roles under noise once a listing base grows past a few thousand postings.",
    approach: [
      "Built a Spring Boot backend exposing job and candidate data through a MySQL-backed schema, with a React.js frontend for search, filtering, and browsing.",
      "Designed a custom ranking algorithm to score job listings against candidate profiles, replacing simple keyword or recency-based sorting.",
      "Added dynamic search filters so candidates can narrow results by role, skill, and other structured attributes.",
      "Implemented real-time notifications to alert candidates when new listings match their profile.",
    ],
    key_decisions: [
      { title: "Ranking", body: "Custom ranking algorithm scores listings against candidate profiles instead of relying on recency or raw keyword match." },
      { title: "Architecture", body: "Spring Boot REST backend with MySQL persistence, consumed by a decoupled React.js frontend." },
      { title: "Search UX", body: "Dynamic filters let candidates narrow a large listing set to what's actually relevant to them." },
      { title: "Notifications", body: "Real-time alerts close the loop when a new listing matches an existing candidate profile." },
    ],
    metrics: [
      { value: "30%", label: "Better job matching accuracy" },
      { value: "10,000+", label: "Listings ranked" },
    ],
    learned:
      "Ranking quality matters more than search UI polish — the biggest lift in perceived relevance came from the scoring algorithm, not the filters around it.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 0,
  },
  {
    slug: "ash-os",
    title: "ASH OS",
    category: "Systems · Operating System",
    description:
      "A custom lightweight operating system built from scratch in C and x86-64 assembly, with kernel-level secure file access policies.",
    stack: ["C", "Assembly", "x86-64"],
    visual: "terminal",
    problem:
      "Understanding an operating system from documentation and source-reading alone only goes so far — writing a kernel forces you to confront boot sequencing, memory layout, and access control at the lowest level.",
    approach: [
      "Wrote a custom bootloader and kernel in C and x86-64 assembly, without relying on an existing OS framework.",
      "Optimized the boot sequence for faster startup relative to a baseline unoptimized boot path.",
      "Implemented kernel-level file access policies to enforce secure access at the system level rather than in user space.",
      "Documented the architecture, kernel security model, and boot optimization approach, which became the basis of a published academic paper.",
    ],
    key_decisions: [
      { title: "Architecture", body: "Bare-metal kernel written directly in C and x86-64 assembly, with explicit control over boot and memory layout." },
      { title: "Performance", body: "Boot sequence optimized specifically for faster startup time." },
      { title: "Security", body: "File access policies enforced at kernel level, not bolted on afterward in user space." },
    ],
    metrics: [],
    learned:
      "Working below the OS abstraction layer changes how you reason about every layer above it — a lot of 'best practices' in application code exist to compensate for constraints you only see once you've written the kernel yourself.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 1,
  },
  {
    slug: "neuro-coder",
    title: "Neuro Coder",
    category: "AI · Developer Tools",
    description: "An AI-powered coding assistant for writing, debugging, and understanding code.",
    stack: ["AI", "JavaScript", "React"],
    visual: "agent-graph",
    problem:
      "Developers lose time context-switching between writing code, debugging it, and understanding unfamiliar code — an assistant that only does one of these is only partially useful.",
    approach: [
      "Built a React-based interface for an AI coding assistant covering three workflows: writing new code, debugging existing code, and explaining unfamiliar code.",
      "Used JavaScript throughout the client to keep the assistant's interaction loop fast and responsive.",
    ],
    key_decisions: [
      { title: "AI / Automation", body: "Assistant is scoped to three concrete developer workflows — write, debug, understand — rather than a general-purpose chat interface." },
      { title: "Interface", body: "React front end keeps the assistant close to the code it's helping with." },
    ],
    metrics: [],
    learned: "Scoping an AI assistant to specific developer workflows produces more useful output than a general-purpose prompt box.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 2,
  },
  {
    slug: "coding-session-tracker",
    title: "Coding Session Tracker",
    category: "Developer Tools · VS Code Extension",
    description:
      "A VS Code extension for understanding real coding behavior through session activity, debugging, file activity, and active coding time.",
    stack: ["TypeScript", "VS Code API"],
    visual: "dashboard",
    problem:
      "Time-tracking tools built outside the editor miss what actually happens during a coding session — how much time goes to active coding versus debugging, and which files actually get touched.",
    approach: [
      "Built a VS Code extension using the VS Code Extension API and TypeScript to observe editor activity directly.",
      "Tracked active coding time, debugging sessions, and file-level activity as they happen inside the editor.",
      "Surfaced session data back to the developer to give visibility into real coding behavior rather than self-reported estimates.",
    ],
    key_decisions: [
      { title: "Architecture", body: "Runs as a VS Code extension, hooking directly into editor and debug session events via the VS Code API." },
      { title: "Data model", body: "Distinguishes active coding time, debugging time, and file activity instead of a single undifferentiated 'time tracked' number." },
    ],
    metrics: [],
    learned: "Self-reported time tracking and editor-observed time tracking rarely agree — the gap itself turned out to be the most useful signal.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 3,
  },
  {
    slug: "taskitect",
    title: "Taskitect",
    category: "Product · Project Management",
    description: "A collaborative task and project management application with boards, deadlines, and team workflows.",
    stack: ["React", "Node.js", "MongoDB"],
    visual: "kanban",
    problem: "Small teams often outgrow a plain to-do list before they need the overhead of a full enterprise project management suite.",
    approach: [
      "Built a Node.js and MongoDB backend for storing boards, tasks, deadlines, and team membership.",
      "Built a React frontend for board-based task organization and team collaboration.",
      "Modeled deadlines and team workflows directly rather than treating them as metadata bolted onto a generic task list.",
    ],
    key_decisions: [
      { title: "Architecture", body: "MERN-style split — React client, Node.js API, MongoDB for flexible document storage of boards and tasks." },
      { title: "Collaboration", body: "Boards and team workflows are first-class, not an afterthought added to a single-user task list." },
    ],
    metrics: [],
    learned: "Board-based structure maps naturally onto how small teams actually think about work in progress versus done.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 4,
  },
  {
    slug: "trackie",
    title: "Trackie",
    category: "Product · Personal Finance",
    description: "Real-time financial insights for personal spending and savings, with encryption and automated backup.",
    stack: ["MongoDB", "Express", "React", "Node.js"],
    visual: "finance",
    problem: "Personal finance data is sensitive by default, so a tracking tool needs to treat security and durability as core requirements, not add-ons.",
    approach: [
      "Built a MERN-stack application (MongoDB, Express, React, Node.js) for tracking personal financial activity.",
      "Delivered real-time financial insights to users as their data changes.",
      "Added encryption for stored financial data and automated backups to protect against data loss.",
    ],
    key_decisions: [
      { title: "Architecture", body: "Full MERN stack — Express/Node.js API, MongoDB storage, React client." },
      { title: "Security", body: "Financial data encrypted at rest, with automated backups guarding against loss." },
      { title: "Real-time insights", body: "Financial summaries update as new activity comes in, instead of on a fixed batch schedule." },
    ],
    metrics: [{ value: "1,500+", label: "Users" }],
    learned: "For data this sensitive, encryption and backups aren't features to add later — they shape the schema and data flow from day one.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 5,
  },
  {
    slug: "electron-app-maker",
    title: "Electron App Maker",
    category: "Developer Tools · Desktop",
    description: "A desktop tool for packaging web applications into native apps, using reusable templates to accelerate web-to-desktop workflows.",
    stack: ["Electron.js", "Node.js"],
    visual: "desktop",
    problem: "Turning an existing web app into a distributable desktop app usually means rebuilding the same Electron boilerplate every time.",
    approach: [
      "Built a tool on Electron.js and Node.js that wraps a web application into a packaged desktop app.",
      "Created reusable templates so the same packaging workflow can be applied across different web apps without starting from scratch each time.",
    ],
    key_decisions: [
      { title: "Reusability", body: "Templates capture the repeatable parts of an Electron packaging workflow so new apps skip the boilerplate." },
      { title: "Scope", body: "Focused specifically on the web-to-desktop packaging step rather than becoming a general Electron framework." },
    ],
    metrics: [],
    learned: "Most of the friction in 'wrap this web app as a desktop app' is repeated setup, not anything specific to the app itself — that's exactly what a template should absorb.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 6,
  },
  {
    slug: "deep-work",
    title: "Deep Work",
    category: "Product · Focus Tool",
    description: "A focus-session tracker inspired by deep-work principles, with session logging and streaks.",
    stack: ["React", "PWA", "Timer"],
    visual: "timer",
    problem: "Generic timer apps track elapsed time but not whether focus sessions actually add up to a sustained practice.",
    approach: [
      "Built as a Progressive Web App in React so it installs and runs like a native app across devices.",
      "Implemented a focus-session timer with logging of completed sessions.",
      "Added streak tracking to reinforce consistency over single-session performance.",
    ],
    key_decisions: [
      { title: "Format", body: "Shipped as a PWA to get installable, app-like behavior without a native app store distribution step." },
      { title: "Behavior model", body: "Streaks and session logs, not just a countdown timer, to reflect deep-work practice as a habit." },
    ],
    metrics: [],
    learned: "A timer alone doesn't build a habit — logging and streaks did more to reinforce consistent use than the timer mechanic itself.",
    link_live: null,
    link_github: null,
    limited_info: false,
    sort_order: 7,
  },
  {
    slug: "qr-code-generator",
    title: "QR Code Generator",
    category: "Developer Tools · QR Codes",
    description: "A customizable QR code creation platform.",
    stack: [],
    visual: "qr-code",
    problem: "",
    approach: [],
    key_decisions: [],
    metrics: [],
    learned: "",
    link_live: null,
    link_github: null,
    limited_info: true,
    sort_order: 8,
  },
  {
    slug: "talkies",
    title: "Talkies",
    category: "Product · Movie Reviews",
    description: "A movie review and rating website.",
    stack: [],
    visual: "product-ui",
    problem: "",
    approach: [],
    key_decisions: [],
    metrics: [],
    learned: "",
    link_live: null,
    link_github: null,
    limited_info: true,
    sort_order: 9,
  },
  {
    slug: "blogsite",
    title: "BlogSite",
    category: "Product · Blogging Platform",
    description: "A Django-based blogging platform.",
    stack: ["Django"],
    visual: "blog",
    problem: "",
    approach: [],
    key_decisions: [],
    metrics: [],
    learned: "",
    link_live: null,
    link_github: null,
    limited_info: true,
    sort_order: 10,
  },
  {
    slug: "dimensionx",
    title: "DimensionX",
    category: "Product · Game",
    description: "An endless mobile/laptop game.",
    stack: [],
    visual: "game",
    problem: "",
    approach: [],
    key_decisions: [],
    metrics: [],
    learned: "",
    link_live: null,
    link_github: null,
    limited_info: true,
    sort_order: 11,
  },
];

export const experienceEntries = [
  {
    kind: "experience",
    company: "Tata Consultancy Services — UBS",
    role: "Assistant System Engineer",
    start_date: "June 2025",
    end_date: "Present",
    location: "Pune, India",
    highlights: [
      "Built an AI-powered Source of Wealth (SoW) verification platform automating client due diligence for UBS, with a Streamlit demo portal showcasing end-to-end AI agent workflows.",
      "Designed the Identification Agent, the entry point extracting claims across 12 Source of Wealth categories for 12 engineering teams.",
      "Built a reusable internal AI framework — shared utilities, guardrails, a documentation portal, and an AI-powered CLI assistant — adopted by 15+ engineering teams.",
      "Recognized by the UBS client with 5,000 Kudos Points for technical contributions.",
      "Promoted to lead the Investment Performance SoW engineering team; improved AI evaluation accuracy from ~60% to ~80% using Knowledge Graph-based retrieval for reports exceeding 100 pages.",
    ],
    sort_order: 0,
  },
  {
    kind: "experience",
    company: "Tata Consultancy Services — UBS",
    role: "Assistant System Engineer, Trainee",
    start_date: "June 2024",
    end_date: "June 2025",
    location: "Pune, India",
    highlights: [
      "Ranked 3rd among 100+ trainees in the final technical assessment.",
      "Built an AI-powered Periodic KYC Review platform automating client verification with OCR and LLMs, using Flask integrated with Spring Boot via REST APIs.",
      "Integrated Azure Document Intelligence, OpenAI APIs, and Flowable to automate KYC document processing.",
      "Built an AI evaluation framework and productionized Splunk dashboards to monitor model performance.",
      "Built a reusable GitLab CI/CD pipeline for deploying multiple repositories through configurable parameters.",
    ],
    sort_order: 1,
  },
  {
    kind: "experience",
    company: "Laptop First",
    role: "Full Stack Engineer",
    start_date: "April 2024",
    end_date: "June 2024",
    location: "Gurugram",
    highlights: [
      "Built and shipped a production-ready laptop subscription platform end to end — landing site, auth, onboarding, customer dashboard, and admin portal.",
      "Led a team of 2 interns through code review and mentoring to hit delivery timelines.",
      "Integrated Aadhaar-based KYC for onboarding and automated recurring subscription billing.",
      "Added configurable RAM/storage selection and researched BIOS-level device locking tied to subscription status.",
    ],
    sort_order: 2,
  },
  {
    kind: "experience",
    company: "The CodeBook Inc.",
    role: "Full Stack Developer",
    start_date: "November 2022",
    end_date: "November 2023",
    location: "Lucknow",
    highlights: [
      "Served as primary technical owner, working directly with the founder to gather requirements and ship releases.",
      "Led a full rewrite of the mobile app after legacy framework limitations blocked critical bug fixes.",
      "Built a reusable UI component library — cards, form fields, validation utilities — to speed up development.",
      "Maintained the company's e-commerce platform, fixing cart/admin backend issues and React frontend bugs.",
      "Received a Letter of Recommendation from the founder for ownership and technical contributions.",
    ],
    sort_order: 3,
  },
  {
    kind: "experience",
    company: "BasketHunt",
    role: "Software Engineer Intern → Team Lead",
    start_date: "April 2023",
    end_date: "June 2023",
    location: null,
    highlights: [
      "Started as Software Engineer Intern designing UI/UX and high-fidelity mockups for an internal LMS and course portal.",
      "Promoted to Team Lead; planned and delegated tasks for the LMS project's delivery.",
      "Led deployment of a self-hosted Moodle instance on Linux for HR compliance and upskilling programs, with documentation structured to onboard future interns.",
    ],
    sort_order: 4,
  },
  {
    kind: "volunteer",
    company: "Tata Consultancy Services",
    role: "Campus Ambassador",
    start_date: "August 2019",
    end_date: "July 2023",
    location: null,
    highlights: [],
    sort_order: 0,
  },
  {
    kind: "volunteer",
    company: "Atypical Advantage",
    role: "Social Media Ambassador",
    start_date: "2021",
    end_date: "2021",
    location: null,
    highlights: [],
    sort_order: 1,
  },
];

export const ventures = [
  {
    name: "Echstatic",
    role: "Founder",
    start_date: "December 2022",
    end_date: "March 2024",
    description: "Educational laboratory website development.",
    sort_order: 0,
  },
];

export const skillGroups = [
  { label: "Languages", skills: ["Java", "Python", "C++", "Bash", "SQL", "JavaScript", "TypeScript"], sort_order: 0 },
  { label: "Backend", skills: ["Spring Boot", "Node.js", "Express.js", "Django", "REST APIs", "JDBC", "MVC"], sort_order: 1 },
  { label: "Frontend", skills: ["React", "React Native", "Tailwind CSS", "Electron", "HTML5", "SASS"], sort_order: 2 },
  {
    label: "AI / ML",
    skills: ["Azure OpenAI", "LangGraph", "RAG", "Azure Document Intelligence", "RAGAS", "OpenAI Evals", "Prompt Engineering", "Prompt Chaining", "Jinja2", "Streamlit"],
    sort_order: 3,
  },
  { label: "Cloud / DevOps", skills: ["AWS", "Azure", "Docker", "GitLab CI/CD", "GitHub Actions", "Cloudflare", "Vercel"], sort_order: 4 },
  { label: "Databases", skills: ["MySQL", "MongoDB", "PostgreSQL"], sort_order: 5 },
  { label: "Systems / Security", skills: ["Linux", "Cryptography", "Reverse Engineering", "Secure File Policies", "OTCC"], sort_order: 6 },
];

function draftBody(outline: string[], code?: { lang: string; code: string }) {
  const lines = [
    "_Draft — this article hasn't been published yet. Planned outline:_",
    "",
    ...outline.map((point) => `- ${point}`),
  ];
  if (code) {
    lines.push("", "A sketch of what's in scope (illustrative only, not production code):", "", "```" + code.lang, code.code, "```");
  }
  return lines.join("\n");
}

export const articles = [
  {
    slug: "reliable-multi-agent-workflows-langgraph",
    category: "AI Engineering",
    title: "Building reliable multi-agent workflows with LangGraph",
    excerpt: "Notes on structuring multi-agent LangGraph workflows so they stay debuggable in production, not just in a demo.",
    reading_time: "8 min read",
    date: "2026-01",
    tags: ["LangGraph", "AI Agents", "Prompt Engineering"],
    outline: [
      "Why a single long prompt breaks down once an agent has more than one responsibility",
      "Structuring a LangGraph workflow around explicit nodes and edges instead of one big chain",
      "Where to put verification and retry logic so one bad step doesn't cascade",
      "What actually needs logging to debug a multi-agent run after the fact",
    ],
    body_markdown: draftBody(
      [
        "Why a single long prompt breaks down once an agent has more than one responsibility",
        "Structuring a LangGraph workflow around explicit nodes and edges instead of one big chain",
        "Where to put verification and retry logic so one bad step doesn't cascade",
        "What actually needs logging to debug a multi-agent run after the fact",
      ],
      { lang: "python", code: `# illustrative — not the production graph\nfrom langgraph.graph import StateGraph\n\ngraph = StateGraph(AgentState)\ngraph.add_node("plan", plan_step)\ngraph.add_node("verify", verify_step)\ngraph.add_edge("plan", "verify")\ngraph.set_entry_point("plan")` }
    ),
    published: false,
    sort_order: 0,
  },
  {
    slug: "ai-verification-pipelines",
    category: "AI Engineering",
    title: "What I learned building AI verification pipelines",
    excerpt: "Getting an LLM to check its own output is harder than it sounds. Notes on building verification pipelines that catch real errors.",
    reading_time: "7 min read",
    date: "2026-02",
    tags: ["RAGAS", "OpenAI Evals", "Evaluation"],
    outline: [
      "Why 'looks right' isn't a verification strategy for AI output at scale",
      "Splitting verification into deterministic checks and model-graded checks",
      "Using RAGAS and OpenAI Evals to score output instead of eyeballing samples",
      "How verification changes what you're willing to automate versus route for review",
    ],
    body_markdown: draftBody([
      "Why 'looks right' isn't a verification strategy for AI output at scale",
      "Splitting verification into deterministic checks and model-graded checks",
      "Using RAGAS and OpenAI Evals to score output instead of eyeballing samples",
      "How verification changes what you're willing to automate versus route for review",
    ]),
    published: false,
    sort_order: 1,
  },
  {
    slug: "prompts-to-production",
    category: "AI Engineering",
    title: "From prompts to production: making AI systems measurable",
    excerpt: "A prompt that works once isn't a system. Notes on turning ad-hoc prompting into something you can measure and trust.",
    reading_time: "9 min read",
    date: "2026-03",
    tags: ["Prompt Engineering", "Evaluation", "Production AI"],
    outline: [
      "The gap between a prompt that works in a notebook and one that holds up in production",
      "Turning prompt iteration into something measurable instead of vibes-based tweaking",
      "What a regression suite for prompts actually looks like",
      "Deciding when a prompt change is safe to ship without a human re-checking every case",
    ],
    body_markdown: draftBody([
      "The gap between a prompt that works in a notebook and one that holds up in production",
      "Turning prompt iteration into something measurable instead of vibes-based tweaking",
      "What a regression suite for prompts actually looks like",
      "Deciding when a prompt change is safe to ship without a human re-checking every case",
    ]),
    published: false,
    sort_order: 2,
  },
  {
    slug: "building-a-tiny-os",
    category: "Systems",
    title: "Building a tiny operating system to understand computers better",
    excerpt: "Notes from writing ASH OS in C and x86-64 assembly, and what it taught me about the layers above the kernel.",
    reading_time: "10 min read",
    date: "2026-04",
    tags: ["Operating Systems", "C", "x86-64"],
    outline: [
      "Why reading OS theory only gets you so far without writing a boot sequence yourself",
      "What actually happens between power-on and a kernel that can run code",
      "Enforcing file access policy at the kernel level instead of in user space",
      "What writing ASH OS changed about how I think about the software layers above it",
    ],
    body_markdown: draftBody(
      [
        "Why reading OS theory only gets you so far without writing a boot sequence yourself",
        "What actually happens between power-on and a kernel that can run code",
        "Enforcing file access policy at the kernel level instead of in user space",
        "What writing ASH OS changed about how I think about the software layers above it",
      ],
      { lang: "asm", code: `; illustrative — simplified boot-stage excerpt\nbits 16\norg 0x7c00\n\nstart:\n    cli\n    xor ax, ax\n    mov ds, ax\n    mov es, ax\n    jmp load_kernel` }
    ),
    published: false,
    sort_order: 3,
  },
  {
    slug: "production-api-optimization",
    category: "Software Engineering",
    title: "What production API optimization actually looks like",
    excerpt: "Performance work rarely looks like a single clever fix. Notes on where API latency actually goes and what moves the number.",
    reading_time: "6 min read",
    date: "2026-05",
    tags: ["APIs", "Performance", "Backend"],
    outline: [
      "Why 'add caching' is rarely the first fix that actually moves latency",
      "Finding out where time actually goes before optimizing anything",
      "The unglamorous fixes that tend to matter more than clever ones — indexing, payload size, N+1 calls",
      "How monitoring changes what you optimize next instead of guessing",
    ],
    body_markdown: draftBody([
      "Why 'add caching' is rarely the first fix that actually moves latency",
      "Finding out where time actually goes before optimizing anything",
      "The unglamorous fixes that tend to matter more than clever ones — indexing, payload size, N+1 calls",
      "How monitoring changes what you optimize next instead of guessing",
    ]),
    published: false,
    sort_order: 4,
  },
  {
    slug: "what-i-learned-building-developer-tools",
    category: "Developer Tools",
    title: "What I learned building developer tools",
    excerpt: "Notes on building small tools for developers — a VS Code extension, a packaging tool — and what makes them worth keeping open.",
    reading_time: "6 min read",
    date: "2026-06",
    tags: ["Developer Tools", "VS Code", "Electron"],
    outline: [
      "What makes a small developer tool worth keeping open versus getting closed after a day",
      "Building on the VS Code Extension API without fighting the editor's own model",
      "What packaging a web app as a desktop app with Electron actually takes, template by template",
      "The difference between a tool built for yourself and one built to hand to someone else",
    ],
    body_markdown: draftBody([
      "What makes a small developer tool worth keeping open versus getting closed after a day",
      "Building on the VS Code Extension API without fighting the editor's own model",
      "What packaging a web app as a desktop app with Electron actually takes, template by template",
      "The difference between a tool built for yourself and one built to hand to someone else",
    ]),
    published: false,
    sort_order: 5,
  },
];

export const publications = [
  {
    kind: "Book",
    title: "The Basics of AI and IoT: A Beginner's Handbook",
    description: "An introductory handbook making AI and IoT accessible to newcomers and students.",
    sort_order: 0,
  },
  {
    kind: "Paper",
    title: "ASH OS: A Comprehensive Linux-Based Operating System with Optimized User Interface",
    description: "Academic paper covering the architecture, kernel security, and boot optimization of a custom x86-64 operating system.",
    sort_order: 1,
  },
  {
    kind: "IP",
    title: "Smart Industrial Robot",
    description: "Registered design / intellectual property (Class 15-99).",
    sort_order: 2,
  },
];

export const achievements = [
  { title: "Silver Medal — 2nd Rank", org: "B.Tech CSE, SRM University Delhi-NCR (AY 2022–2023)", featured: true, sort_order: 0 },
  { title: "Star of the Month", org: "Tata Consultancy Services · August 2025", featured: false, sort_order: 1 },
  { title: "On The Spot Award", org: "Tata Consultancy Services · January 2026", featured: false, sort_order: 2 },
  { title: "Galactic Problem Solver", org: "Tata Consultancy Services", featured: false, sort_order: 3 },
  { title: "Certificate of Appreciation", org: "Tata Consultancy Services", featured: false, sort_order: 4 },
  { title: "DIAT / DRDO Cyber Security Certification", org: "Score: 80.4/100", featured: false, sort_order: 5 },
];

export const certifications = [
  { title: "Master Class on Data Science", issuer: null, date: null, sort_order: 0 },
  { title: "Demonstrating Theoretical and Practical Understanding of SQL", issuer: null, date: null, sort_order: 1 },
  { title: "CSS Certificate", issuer: null, date: null, sort_order: 2 },
  { title: "C++ Tutorial Certificate", issuer: null, date: null, sort_order: 3 },
  { title: "Certificate of Participation in Jumpstart", issuer: null, date: null, sort_order: 4 },
];

export const siteSettings = {
  id: 1,
  name: "Abhijat",
  role: "AI Engineer · Full-Stack Software Engineer · Published Author",
  tagline: "AI Systems · Full-Stack Development · Cloud · Developer Tools",
  location: "India",
  email: "abhijat.tech@gmail.com",
  github: "https://github.com/Abhijat-Abhijat",
  linkedin: "https://linkedin.com/in/abhijat-profile",
  status: "Building AI systems",
  site_url: "https://abhijat.co.in",
};
